$kind: http-request
name: Get All Tasks
method: GET
url: '{{baseUrl}}/api/tasks'
order: 1000
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{authToken}}'
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      // Implement when task routes are active
